import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
await fs.mkdir('.impeccable/review',{recursive:true});await fs.mkdir('docs',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-precise-memory-info']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/science');await page.getByText(/6 VFB reconstructions/).waitFor();await page.waitForTimeout(1500);
const hash=async(label)=>page.getByLabel(label,{exact:true}).evaluate(async c=>{const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',a))).map(x=>x.toString(16).padStart(2,'0')).join('');});
const initialOriginal=await hash('Original processed source frame'),initialRetina=await hash('Modelled retinal stimulus');
await page.waitForTimeout(800);assert.notEqual(await hash('Original processed source frame'),initialOriginal);assert.notEqual(await hash('Modelled retinal stimulus'),initialRetina);
await page.waitForTimeout(400);const response1=await page.locator('.activity-inspector strong').textContent();await page.waitForTimeout(650);const response2=await page.locator('.activity-inspector strong').textContent();
await page.getByRole('button',{name:'Pause processing',exact:true}).click();const frozen=await hash('Modelled retinal stimulus'),frozenOriginal=await hash('Original processed source frame');await page.waitForTimeout(400);assert.equal(await hash('Modelled retinal stimulus'),frozen);assert.equal(await hash('Original processed source frame'),frozenOriginal);
await page.getByRole('button',{name:'4 Motion channels'}).click();assert.notEqual(await hash('Modelled retinal stimulus'),frozen);await page.getByRole('button',{name:'1 Retinal sampling'}).click();
await page.getByLabel('Source timeline',{exact:true}).fill('0');await page.getByLabel('Source timeline',{exact:true}).dispatchEvent('input');await page.getByLabel('Source timeline',{exact:true}).dispatchEvent('change');await page.waitForTimeout(100);assert.equal(await page.locator('.activity-inspector strong').textContent(),'0.000');await page.getByRole('button',{name:'Play processing',exact:true}).click();await page.getByRole('button',{name:'T5a',exact:true}).click();assert.match(await page.locator('.neuron-identity').innerText(),/VFB_00104dxc/);
await page.getByRole('button',{name:'T4a',exact:true}).click();
const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,perf:document.querySelector('.performance').textContent}));assert.ok(layout.scroll<=layout.width);
await page.screenshot({path:'.impeccable/review/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Evidence',exact:true}).click();assert.ok(await page.getByRole('dialog',{name:'Evidence inspector'}).isVisible());await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog',{name:'Evidence inspector'}).count(),0);
await page.getByRole('button',{name:'Parameters'}).click();const spacing=page.getByText(/^Sampling/).locator('input');await spacing.fill('6');await spacing.dispatchEvent('input');await spacing.dispatchEvent('change');await page.getByRole('button',{name:'Reset model',exact:true}).click();await page.getByRole('button',{name:'Parameters'}).click();
// Generate a locally authored neutral WebM fixture through the real browser encoder.
const sampleBase64=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=768;canvas.height=432;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(30);const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8',videoBitsPerSecond:900000});const chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise(resolve=>{recorder.onstop=resolve;});recorder.start();let i=0;const timer=setInterval(()=>{ctx.fillStyle='#243438';ctx.fillRect(0,0,768,432);for(let x=-100;x<900;x+=100){ctx.fillStyle='#d1dcd5';ctx.fillRect((x+i*3)%900-100,0,44,432);}i++;},1000/30);await new Promise(r=>setTimeout(r,4000));recorder.stop();await stopped;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:'video/webm'});const bytes=new Uint8Array(await blob.arrayBuffer());let text='';for(const b of bytes)text+=String.fromCharCode(b);return btoa(text);});
await fs.writeFile('docs/qa-sample.webm',Buffer.from(sampleBase64,'base64'));await page.waitForTimeout(800);
await page.locator('input[type=file]').setInputFiles('docs/qa-sample.webm');await page.waitForTimeout(800);assert.equal(await page.locator('.status').innerText(),'LOCAL VIDEO');const local1=await hash('Modelled retinal stimulus');await page.waitForTimeout(500);console.log('local video',await page.evaluate(()=>({time:document.querySelector('video').currentTime,paused:document.querySelector('video').paused,notice:document.querySelector('.notice')?.textContent,stats:document.querySelector('.performance').textContent})),local1,await hash('Modelled retinal stimulus'));assert.notEqual(await hash('Modelled retinal stimulus'),local1);
// Denial path uses a standards-shaped fixture; never capture the user's desktop.
await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{configurable:true,value:()=>Promise.reject(new DOMException('Cancelled by QA fixture','NotAllowedError'))});});
await page.getByRole('button',{name:'Share tab',exact:true}).click();await page.getByText('Sharing was cancelled or denied.',{exact:false}).waitFor();assert.equal(await page.locator('.status').innerText(),'LOCAL VIDEO');
// Success and ended-track path: deterministic synthetic MediaStream fixture.
await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{configurable:true,value:async()=>{const c=document.createElement('canvas');c.width=768;c.height=432;const ctx=c.getContext('2d');let n=0;window.qaCaptureTimer=setInterval(()=>{ctx.fillStyle=n++%2?'white':'black';ctx.fillRect(0,0,768,432);},120);const s=c.captureStream(30);window.qaCapture=s;return s;}});});
await page.getByRole('button',{name:'Share tab',exact:true}).click();await page.waitForTimeout(700);assert.equal(await page.locator('.status').innerText(),'LIVE CAPTURE');const captured1=await hash('Original processed source frame');await page.waitForTimeout(200);const captured2=await hash('Original processed source frame');
await page.evaluate(()=>{const track=window.qaCapture.getVideoTracks()[0];track.stop();track.dispatchEvent(new Event('ended'));clearInterval(window.qaCaptureTimer);});await page.getByText('Sharing stopped.',{exact:false}).waitFor();assert.equal(await page.locator('.status').innerText(),'CAPTURE REQUIRED');assert.ok(await page.getByTitle('Official JesusAVGN Kick player').isVisible());
await page.screenshot({path:'.impeccable/review/kick-capture-required.png',fullPage:true});
await page.getByRole('button',{name:'Sample',exact:true}).click();await page.getByRole('button',{name:'Real fly experiment',exact:true}).click();assert.ok(await page.getByText('No experimental hardware connected',{exact:true}).isVisible());await page.getByRole('button',{name:'Digital fly',exact:true}).click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);const mobile=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(mobile.scroll<=mobile.width);await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});
await page.getByRole('button',{name:'Evidence',exact:true}).click();await page.screenshot({path:'.impeccable/review/mobile-evidence.png',fullPage:true});await page.getByRole('button',{name:'Close evidence inspector'}).click();
await page.setViewportSize({width:1440,height:1000});await page.getByRole('combobox',{name:'Test stimulus'}).selectOption('static');await page.waitForTimeout(1500);const staticMetrics=await page.locator('.activity-inspector strong').textContent();assert.ok(Number(staticMetrics)<.005);
await page.getByRole('combobox',{name:'Test stimulus'}).selectOption('grating');
const memory=[];for(let i=0;i<6;i++){await page.waitForTimeout(5000);memory.push(await page.evaluate(()=>({heap:performance.memory?.usedJSHeapSize,performance:document.querySelector('.performance').textContent,canvases:document.querySelectorAll('canvas').length})));}
assert.ok(memory.every(m=>m.canvases===5));assert.equal(errors.length,0,errors.join('\n'));
await fs.writeFile('docs/browser-results.json',JSON.stringify({at:new Date().toISOString(),errors,layout,mobile,sourceFramesChange:true,retinaFramesChange:true,pauseFreezesBoth:true,response1,response2,localVideoDecoded:true,captureFixture:{denied:true,success:true,ended:true,captured1,captured2},realPicker:'Not automated; explicit user browser choice required',staticMetrics,memory},null,2));
console.log(JSON.stringify({passed:true,layout,mobile,errors,memory},null,2));await browser.close();


