import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-precise-memory-info']});
const uploadTitle=`QA owned video ${Date.now()}`;
const results={at:new Date().toISOString(),errors:[],checks:[],screenshots:[],performance:[],limits:['No real KICK OAuth credentials or live broadcast used','TTS API dispatch checked; OS voice audibility not certified','Capture fixture is locally authored video, not user desktop']};
const check=name=>{results.checks.push(name);console.log('PASS',name);};
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>results.errors.push(e.message));
 await page.addInitScript(()=>{window.qaSpoken=[];window.qaCancels=0;Object.defineProperty(speechSynthesis,'speak',{value:u=>{window.qaSpoken.push(u.text);u.onstart?.();}});Object.defineProperty(speechSynthesis,'cancel',{value:()=>{window.qaCancels++;}});});
 await page.goto('http://127.0.0.1:5173/control');await page.getByRole('heading',{name:'Live',exact:true}).waitFor();
 const api=async(type,payload={})=>page.evaluate(async({type,payload})=>{const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,payload})});return{status:r.status,...await r.json()};},{type,payload});
 const snapshot=()=>page.evaluate(async()=>await(await fetch('/api/state')).json());
 await api('safe');await api('resume');await api('mode',{mode:'ASSISTED'});await api('settings',{speechCooldownSeconds:5,directorIntervalSeconds:600,voiceEnabled:true});await page.waitForTimeout(1800);
 const hash=async(p,label)=>p.getByLabel(label,{exact:true}).evaluate(async c=>{const bytes=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].join(',');});
 const before=await hash(page,'Stream source frame');await page.waitForTimeout(700);assert.notEqual(await hash(page,'Stream source frame'),before);assert.ok((await snapshot()).signals.at>0);check('Actual video frames update and feed model signals');
 const pov=await hash(page,'Stream fly POV');assert.ok(pov.length>20);await page.waitForTimeout(400);check('Fly POV is computed and visible');
 const output=await context.newPage();output.on('pageerror',e=>results.errors.push(e.message));await output.goto('http://127.0.0.1:5173/stream?audio=0');await output.setViewportSize({width:1920,height:1080});await output.waitForTimeout(900);assert.equal(await output.getByRole('button').filter({visible:true}).count(),0);check('Clean OBS output has no operator controls');
 await api('mood',{mood:'SCARED'});await page.waitForTimeout(350);assert.equal(await output.locator('.broadcast-scene').getAttribute('data-mood'),'SCARED');const scared=await output.locator('.fly-canvas canvas').screenshot();await api('mood',{mood:'SLEEPY'});await page.waitForTimeout(450);assert.notDeepEqual(await output.locator('.fly-canvas canvas').screenshot(),scared);check('Shared moods change actual 3D rendering across routes');
 await page.getByRole('button',{name:'Chat',exact:true}).click();await page.getByLabel('Demo viewer',{exact:true}).fill('QAViewer');await page.getByLabel('Message or command',{exact:true}).fill('!dance');await page.getByRole('button',{name:'Send demo',exact:true}).click();await page.waitForTimeout(350);assert.ok((await snapshot()).actions.some(a=>a.event==='!dance'));const count=(await snapshot()).actions.filter(a=>a.event==='!dance').length;await api('chat',{userId:'demo-qaviewer',name:'QAViewer',text:'!dance'});assert.equal((await snapshot()).actions.filter(a=>a.event==='!dance').length,count);check('Mock chat command works with duplicate cooldown');
 await api('chat',{userId:'unsafe-fixture',name:'Fixture',text:'kill yourself'});assert.ok((await snapshot()).analytics.messagesBlocked>0);assert.ok((await page.evaluate(()=>window.qaSpoken)).every(t=>!t.includes('kill yourself')));check('Unsafe viewer TTS is blocked');
 const realBefore=(await snapshot()).monetization.real;await page.getByRole('button',{name:'Events',exact:true}).click();await page.getByRole('button',{name:'Demo subscription',exact:true}).click();await page.getByRole('button',{name:'Demo $5 tip',exact:true}).click();const money=await snapshot();assert.ok(money.monetization.demo.subscriptions>0);assert.ok(money.monetization.demo.tipCount>0);assert.deepEqual(money.monetization.real,realBefore);assert.ok(money.clips.length>0);check('Demo sub/tip reactions and clip markers work without fake real revenue');
 await api('poll_create',{question:'QA next?',options:['Grating','Loom'],duration:10});const poll=(await snapshot()).poll;assert.equal((await api('poll_vote',{option:poll.options[0].id,userId:'qa-poll'})).ok,true);assert.equal((await api('poll_vote',{option:poll.options[1].id,userId:'qa-poll'})).ok,false);check('Poll records actual votes and rejects duplicate viewer');
 await api('game_start',{type:'findfood'});const game=(await snapshot()).game;assert.equal((await api('game_vote',{choice:game.target,userId:'qa-game',name:'GameFixture'})).ok,true);assert.equal((await api('game_vote',{choice:game.target,userId:'qa-game',name:'GameFixture'})).ok,false);check('Find food scores actual one-attempt game input');
 await page.getByRole('button',{name:'Content',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill(uploadTitle);await page.getByLabel('Rights basis',{exact:true}).selectOption('owned');await page.getByLabel('Attribution / permission record',{exact:true}).fill('FlyStream Lab · authored test fixture');await page.getByLabel(/I have checked/).check();await page.getByLabel('Local media',{exact:true}).setInputFiles('public/sample.webm');await page.getByRole('button',{name:'Add to queue',exact:true}).click();await page.getByRole('button',{name:`Play ${uploadTitle}`,exact:true}).waitFor({timeout:15000});const item=(await snapshot()).queue.find(x=>x.title===uploadTitle);assert.ok(item.duration>0);await page.getByRole('button',{name:`Play ${uploadTitle}`,exact:true}).click();await page.waitForTimeout(700);assert.ok(await output.locator('.broadcast-credit').innerText());check('Local upload uses real duration, rights gate and on-air attribution');
 await page.waitForTimeout(800);const videoTime=await output.locator('video').evaluate(v=>v.currentTime);await api('queue_play',{id:item.id});await page.waitForTimeout(250);assert.ok(await output.locator('video').evaluate(v=>v.currentTime)<videoTime);check('Replaying current content resets OBS decoder');
 const blocked=await api('queue_add',{title:'QA uncleared',source:'url',url:'https://example.com/unverified.mp4',license:'unknown',permission:false,duration:20});const unsafe=blocked.state.queue.at(-1);assert.equal((await api('queue_play',{id:unsafe.id})).ok,false);check('Unverified rebroadcast content cannot go on air');
 await page.evaluate(()=>{Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{configurable:true,value:async()=>{const c=document.createElement('canvas');c.width=1280;c.height=720;const ctx=c.getContext('2d');window.qaPaint=color=>{ctx.fillStyle=color;ctx.fillRect(0,0,1280,720);};window.qaPaint('#00bb55');window.qaCapture=c.captureStream(15);return window.qaCapture;}});});
 await page.getByRole('button',{name:'Share permitted tab',exact:true}).click();await page.getByRole('button',{name:'Stop tab sharing',exact:true}).waitFor();await page.waitForTimeout(900);const capture1=await hash(output,'Stream source frame');await page.getByRole('button',{name:'Live',exact:true}).click();await page.evaluate(()=>window.qaPaint('#aa2255'));await page.waitForTimeout(1100);assert.notEqual(await hash(output,'Stream source frame'),capture1);check('Capture JPEG relay crosses routes and survives panel navigation');
 await page.evaluate(()=>{const t=window.qaCapture.getVideoTracks()[0];t.stop();t.dispatchEvent(new Event('ended'));});await page.waitForTimeout(3600);assert.match(await output.locator('.broadcast-footer').innerText(),/Shared source ended/);check('Ended capture expires and shows a safe source');
 await api('queue_play',{id:'sample-loop'});await api('mode',{mode:'MANUAL'});await api('mood',{mood:'EXCITED'});await page.waitForTimeout(250);await page.getByRole('button',{name:'Clips',exact:true}).click();await page.getByRole('button',{name:'Record vertical clips',exact:true}).click();await page.waitForTimeout(1800);await page.getByRole('button',{name:'Stop recording',exact:true}).click();await page.getByRole('button',{name:'Download video',exact:true}).first().waitFor();const d=page.waitForEvent('download');await page.getByRole('button',{name:'Download video',exact:true}).first().click();const download=await d;await download.saveAs('.impeccable/review/qa-vertical.webm');assert.ok((await fs.stat('.impeccable/review/qa-vertical.webm')).size>1000);check('Vertical WebM recorder exports a complete nonempty video');
 const file=await fs.readFile('.impeccable/review/qa-vertical.webm');const decoded=await page.evaluate(async base64=>{const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'video/webm'}));const v=document.createElement('video');v.muted=true;v.src=url;document.body.append(v);try{await new Promise((r,j)=>{v.onloadeddata=r;v.onerror=j;});await v.play();await new Promise(r=>setTimeout(r,300));return{width:v.videoWidth,height:v.videoHeight,time:v.currentTime};}finally{v.pause();v.remove();URL.revokeObjectURL(url);}},file.toString('base64'));assert.equal(decoded.width,720);assert.equal(decoded.height,1280);assert.ok(decoded.time>0);check('Exported WebM decodes at 9:16');
 await api('mode',{mode:'ASSISTED'});await page.getByRole('button',{name:'Live',exact:true}).click();await page.waitForTimeout(5500);await api('demo_event',{type:'follow',name:'VoiceFixture'});await page.waitForTimeout(350);assert.ok((await page.evaluate(()=>window.qaSpoken)).length>0);const canceled=await page.evaluate(()=>window.qaCancels);await api('voice_interrupt');await page.waitForTimeout(250);assert.ok(await page.evaluate(()=>window.qaCancels)>canceled);check('Voice dispatch and shared speech interruption work');
 await page.getByRole('button',{name:'Emergency safe mode',exact:true}).click();await page.waitForTimeout(300);assert.equal((await snapshot()).safe,true);assert.equal(await output.locator('.broadcast-scene').getAttribute('data-safe'),'true');assert.equal(await output.locator('video').evaluate(v=>v.paused),true);assert.equal(await output.locator('.broadcast-subtitles').count(),0);check('Emergency safe mode stops media, speech and retains the output shell');
 await page.screenshot({path:'.impeccable/review/control-safe.png',fullPage:true});await output.screenshot({path:'.impeccable/review/stream-safe.png'});
 await api('resume');await api('mode',{mode:'ASSISTED'});await page.waitForTimeout(500);await page.screenshot({path:'.impeccable/review/control-desktop.png',fullPage:true});await output.screenshot({path:'.impeccable/review/stream-desktop.png'});
 for(const width of [390,320]){await page.setViewportSize({width,height:844});for(const tab of ['Live','Content','Events','Clips','Settings']){await page.getByRole('button',{name:tab,exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width} ${tab} overflow`);}await page.getByRole('button',{name:'Live',exact:true}).click();await page.screenshot({path:`.impeccable/review/control-mobile-${width}.png`,fullPage:true});}check('390/320 px control panels remain usable without horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Debug',exact:true}).click();await page.screenshot({path:'.impeccable/review/control-debug.png',fullPage:true});await page.getByRole('button',{name:'Events',exact:true}).click();await page.screenshot({path:'.impeccable/review/control-events.png',fullPage:true});
 const science=await context.newPage();science.on('pageerror',e=>results.errors.push(e.message));await science.goto('http://127.0.0.1:5173/science');await science.getByText('6 VFB reconstructions').waitFor();const science1=await hash(science,'Original processed source frame');await science.waitForTimeout(500);assert.notEqual(await hash(science,'Original processed source frame'),science1);await science.close();check('Existing scientific workbench and actual VFB remain functional');
 for(let i=0;i<3;i++){await output.waitForTimeout(5000);results.performance.push(await output.evaluate(()=>({fps:document.querySelector('.fly-canvas canvas').dataset.fps,drawCalls:document.querySelector('.fly-canvas canvas').dataset.drawCalls,triangles:document.querySelector('.fly-canvas canvas').dataset.triangles,canvases:document.querySelectorAll('canvas').length,heap:performance.memory?.usedJSHeapSize})));}
 assert.equal(results.errors.length,0,results.errors.join('\n'));check('No unexpected page errors');await fs.writeFile('docs/streamer-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({passed:true,checks:results.checks,performance:results.performance},null,2));
}finally{await browser.close();}


