import { useEffect,useRef,useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RotateCcw } from 'lucide-react';
import { parseSWC,type Neuron } from './vfb';
import type { Metrics } from './engine';
export function Anatomy({neurons,selected,onSelect,metrics,overlay}:{neurons:Neuron[];selected:string;onSelect:(id:string)=>void;metrics:React.RefObject<Metrics>;overlay:boolean}){
 const host=useRef<HTMLDivElement>(null),selection=useRef(selected),showActivity=useRef(overlay),reset=useRef<()=>void>(()=>{});const [error,setError]=useState(''),[loaded,setLoaded]=useState(0);
 selection.current=selected;showActivity.current=overlay;
 useEffect(()=>{
  if(!host.current||!neurons.length)return;const mount=host.current;const abort=new AbortController();let disposed=false,raf=0;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{setError('WebGL unavailable. Verified neuron records remain available below.');return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));mount.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','VFB reconstructed neurons. Drag to rotate; scroll to zoom.');renderer.domElement.setAttribute('role','img');
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.autoRotate=false;
  const group=new THREE.Group();scene.add(group);const models:THREE.LineSegments<THREE.BufferGeometry,THREE.LineBasicMaterial>[]=[];let radius=100;
  const fit=()=>{if(!models.length)return;const box=new THREE.Box3().setFromObject(group),center=box.getCenter(new THREE.Vector3());radius=box.getSize(new THREE.Vector3()).length()*.65;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(radius*.3,-radius*.2,radius*1.7));camera.near=Math.max(.01,radius/1000);camera.far=radius*50;camera.updateProjectionMatrix();controls.update();};reset.current=fit;
  Promise.allSettled(neurons.map(async(n,i)=>{const response=await fetch(n.swc,{signal:abort.signal});if(!response.ok)throw new Error(n.id);const segments=parseSWC(await response.text());if(disposed)return;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(segments,3));const material=new THREE.LineBasicMaterial({color:i%2?'#efa88e':'#7bdcc2',transparent:true,opacity:.55});const line=new THREE.LineSegments(geo,material);line.userData={id:n.id,type:n.type};models.push(line);group.add(line);setLoaded(models.length);})).then(results=>{if(disposed)return;fit();if(results.some(r=>r.status==='rejected'))setError('Some skeletons could not load. Retry by reloading or open VFB.');});
  const resize=new ResizeObserver(()=>{const w=mount.clientWidth,h=mount.clientHeight;renderer.setSize(w,h);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();});resize.observe(mount);
  const raycaster=new THREE.Raycaster();raycaster.params.Line={threshold:2};let down:{x:number;y:number}|null=null;
  const pointerDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};
  const click=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.params.Line={threshold:radius*.012};raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=raycaster.intersectObjects(models)[0];if(hit)onSelect(hit.object.userData.id);};
  renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',click);
  renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','VFB reconstructed neurons. Drag or use arrow keys to rotate; plus and minus to zoom.');
  const keyboard=(e:KeyboardEvent)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();const offset=camera.position.clone().sub(controls.target);if(e.key==='+'||e.key==='-')offset.multiplyScalar(e.key==='+'?.9:1.1);else offset.applyAxisAngle(new THREE.Vector3(e.key==='ArrowUp'||e.key==='ArrowDown'?1:0,e.key==='ArrowLeft'||e.key==='ArrowRight'?1:0,0),(e.key==='ArrowLeft'||e.key==='ArrowUp'?1:-1)*.12);camera.position.copy(controls.target).add(offset);controls.update();};renderer.domElement.addEventListener('keydown',keyboard);
  const frame=()=>{if(disposed)return;controls.update();for(const model of models){const active=model.userData.id===selection.current;const response=model.userData.type==='HSE'?metrics.current.right+metrics.current.left:model.userData.type.startsWith('T5')?metrics.current.off:metrics.current.on;model.material.opacity=active?.95:.24;model.material.color.set(model.userData.type.startsWith('T5')?'#efa88e':'#79d6bc');if(showActivity.current&&active){model.material.color.lerp(new THREE.Color('#ffe4a4'),Math.min(1,response*3));model.material.opacity=.45+Math.min(.55,response*2);}}renderer.render(scene,camera);raf=requestAnimationFrame(frame);};frame();
  return()=>{disposed=true;abort.abort();cancelAnimationFrame(raf);resize.disconnect();controls.dispose();models.forEach(m=>{m.geometry.dispose();m.material.dispose();});renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',click);renderer.domElement.removeEventListener('keydown',keyboard);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();};
 },[neurons,onSelect,metrics]);
 return <div className="anatomy-wrap"><div className="anatomy-canvas" ref={host}/><div className="anatomy-note">{error|| (loaded?`${loaded} VFB reconstructions`:'Loading verified anatomy…')}</div><button className="reset-camera icon-button" aria-label="Reset anatomy view" onClick={()=>reset.current()}><RotateCcw size={15}/></button><div className="anatomy-axis">JRC2018Unisex <span>drag / zoom</span></div></div>;
}
