export const sources = [
  {id:'sampling',title:'Optics & spatial sampling',category:'MODELLED',citation:'Juusola et al. · eLife · 2017',url:'https://elifesciences.org/articles/26117',detail:'Approximately 750 ommatidia per eye and an average interommatidial angle of 4.5°. This engine samples only the displayed angular patch, with a uniform lattice. Neural superposition, retinal micromovements and natural variation are not reconstructed.'},
  {id:'optics',title:'Acceptance & delay model',category:'MODELLED',citation:'Reiser & Dickinson · Journal of Experimental Biology · 2013',url:'https://journals.biologists.com/jeb/article/216/4/719/11876/Visual-motion-speed-determines-a-behavioral-switch',detail:'Published model defaults: 5° acceptance FWHM, 4.5° sampling and 30 ms delay. Gaussian integration precedes sampling. These are modelling choices, not universal physiological constants. Adaptation (200 ms) and display gain are engineering assumptions.'},
  {id:'motion',title:'ON / OFF direction pathways',category:'INFERRED',citation:'Maisak et al. · Nature · 2013',url:'https://www.nature.com/articles/nature12320',detail:'T4 and T5 subtypes respond preferentially to moving ON and OFF edges, respectively, with four direction preferences. Here local delayed correlations generate dimensionless motion features. The anatomy overlay uses ON/OFF contrast drive; it is not fitted cell-specific activity.'},
  {id:'limits',title:'What the correlator leaves out',category:'INFERRED',citation:'Haag, Mishra & Borst · eLife · 2017',url:'https://elifesciences.org/articles/29044',detail:'Real T4/T5 receptive fields combine preferred-direction enhancement and null-direction suppression. This simplified correlator is not a validated circuit simulation. Vertical pairs span two hex rows; cardinal outputs have different sampling baselines.'},
  {id:'spectral',title:'RGB is not fly colour vision',category:'MODELLED',citation:'Salcedo et al. · Journal of Neuroscience · 1999',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6784940/',detail:'R1–R6 express Rh1; R7/R8 have specialized spectral pathways. Ordinary RGB pixels do not record UV or calibrated spectral radiance. Only linear-sRGB luminance is used here: a display proxy, not receptor excitation. R7/UV and exact R8 responses are unavailable.'},
  {id:'spectral-context',title:'Native spectral context matters',category:'SOURCE',citation:'Sharkey et al. · Scientific Reports · 2020',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7588446/',detail:'Screening pigments and native receptor context alter spectral sensitivities. Opsin peak wavelengths alone cannot calibrate an RGB-to-photoreceptor conversion.'},
  {id:'workshop',title:'NeuroFly 2026 / VFB',category:'SOURCE',citation:'Discovery · Visualisation · Connectomics · Putting It Together',url:'https://workshop.virtualflybrain.org/',detail:'Verified structural identities and reconstructions are provided by Virtual Fly Brain. Structural connectivity does not constitute a neuronal recording. The app keeps dataset provenance and model response separate.'},
  {id:'kick',title:'Official Kick playback',category:'SOURCE',citation:'Kick · Embed documentation',url:'https://help.kick.com/en/articles/8010826-how-to-embed-your-kick-livestream',detail:'Official embedded playback is cross-origin. Choose Share tab to grant frame access. Without an authenticated official status service, the app cannot independently verify LIVE / OFFLINE. The player reports playback availability; captured content may be live or a VOD.'},
];
export const stages = [
  {id:'retina',name:'Retinal sampling',short:'Optics → mosaic',evidence:'sampling',description:'Gaussian angular integration → a sampled screen patch. Not a complete eye or a perceptual reconstruction.'},
  {id:'photoreceptor',name:'Photoreceptor proxy',short:'Luminance proxy',evidence:'spectral',description:'Linear-sRGB luminance at each sample. R1–R6-inspired achromatic input; R7/UV and exact R8 excitation are unavailable.'},
  {id:'temporal',name:'Temporal response',short:'ON / OFF',evidence:'optics',description:'Change relative to an adapting baseline. Green: ON contrast; amber: OFF contrast. Adaptation time is a software assumption.'},
  {id:'motion',name:'Motion channels',short:'Directional energy',evidence:'motion',description:'Delayed local correlations: green right, amber left, blue vertical. Dimensionless T4/T5-inspired features, not firing rates.'},
  {id:'downstream',name:'Downstream proxy',short:'Pooled motion',evidence:'limits',description:'Local motion magnitude pooled for display. No synaptic weights, membrane potentials or fitted downstream neuron model.'},
] as const;
