import React,{useCallback,useEffect,useRef,useState} from 'react';

import {Activity,ArrowDown,ArrowLeft,ArrowRight,ArrowUp,BookOpen,Camera,ChevronDown,ExternalLink,Monitor,Pause,Play,Radio,RotateCcw,Settings2,Share2,Upload,X} from 'lucide-react';
import {VisionEngine,defaults,zeroMetrics,type Metrics,type Params,type Stage} from './engine';
import {sources,stages} from './evidence';
import {getAnatomy,type Neuron} from './vfb';
import {Anatomy} from './Anatomy';
import {FlyScene} from './FlyScene';
import {drawSample} from './sample';
import {drawTrace} from './trace';
import {readBroadcastStatus,unknownStatus,type BroadcastStatus} from './source';
import './style.css';
type InputMode='sample'|'kick'|'capture'|'file';
const timecode=(t:number)=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}.${Math.floor(t%1*10)}`;
export function ScienceApp(){
 const [mode,setMode]=useState<InputMode>('sample'),[playing,setPlaying]=useState(true),[stage,setStage]=useState<Stage>('retina'),[params,setParams]=useState<Params>(defaults),[pattern,setPattern]=useState('grating');
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[evidence,setEvidence]=useState<string|null>(null),[advanced,setAdvanced]=useState(false),[experiment,setExperiment]=useState(false),[overlay,setOverlay]=useState(true),[broadcast,setBroadcast]=useState<BroadcastStatus>(unknownStatus);
 const [neurons,setNeurons]=useState<Neuron[]>([]),[selected,setSelected]=useState('VFB_00104bfr'),[anatomyError,setAnatomyError]=useState(''),[fileName,setFileName]=useState(''),[duration,setDuration]=useState(30);
 const [stats,setStats]=useState({metrics:zeroMetrics,fps:0,cost:0,frames:0}),[ended,setEnded]=useState(false);
 const original=useRef<HTMLCanvasElement>(null),retina=useRef<HTMLCanvasElement>(null),trace=useRef<HTMLCanvasElement>(null),video=useRef<HTMLVideoElement>(null),fileInput=useRef<HTMLInputElement>(null);
 const engine=useRef(new VisionEngine()),metrics=useRef<Metrics>(zeroMetrics),time=useRef(0),history=useRef<Metrics[]>([]),stream=useRef<MediaStream|null>(null),objectUrl=useRef(''),resetTiming=useRef(true),totalFrames=useRef(0);
 const config=useRef({mode,playing,stage,params,pattern});config.current={mode,playing,stage,params,pattern};
 const selectedNeuron=neurons.find(n=>n.id===selected);const selectNeuron=useCallback((id:string)=>setSelected(id),[]);
 const activeStage=stages.find(s=>s.id===stage)!;const currentEvidence=sources.find(s=>s.id===evidence);
 const publishStill=useCallback((at?:number)=>{
  const c=config.current,oc=original.current,rc=retina.current;if(!oc||!rc||c.mode==='kick')return;
  const ctx=oc.getContext('2d')!;const stamp=at??time.current;
  if(c.mode==='sample')drawSample(ctx,stamp,c.pattern);
  else {const v=video.current;if(!v||v.readyState<2||v.seeking)return;ctx.fillStyle='#090e10';ctx.fillRect(0,0,768,432);const scale=Math.min(768/v.videoWidth,432/v.videoHeight);ctx.drawImage(v,(768-v.videoWidth*scale)/2,(432-v.videoHeight*scale)/2,v.videoWidth*scale,v.videoHeight*scale);}
  const small=document.createElement('canvas');small.width=192;small.height=108;const sc=small.getContext('2d')!;sc.drawImage(oc,0,0,192,108);engine.current.configure(192,108,c.params);engine.current.reset();
  metrics.current=engine.current.process(sc.getImageData(0,0,192,108).data,33,stamp);time.current=stamp;history.current=[];engine.current.render(rc.getContext('2d')!,c.stage,768,432);const chart=trace.current?.getContext('2d');if(chart)drawTrace(chart,[]);setStats({metrics:{...metrics.current},fps:0,cost:metrics.current.cost,frames:totalFrames.current});
 },[]);
 const stopInput=useCallback(()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current){video.current.pause();video.current.srcObject=null;video.current.removeAttribute('src');video.current.load();}if(objectUrl.current){URL.revokeObjectURL(objectUrl.current);objectUrl.current='';}},[]);
 const reset=useCallback(()=>{engine.current.reset();resetTiming.current=true;history.current=[];metrics.current={...zeroMetrics};time.current=0;setEnded(false);setStats({metrics:{...zeroMetrics},fps:0,cost:0,frames:totalFrames.current});const chart=trace.current?.getContext('2d');if(chart)drawTrace(chart,[]);for(const canvas of [original.current,retina.current]){const ctx=canvas?.getContext('2d');if(ctx){ctx.fillStyle='#090e10';ctx.fillRect(0,0,canvas!.width,canvas!.height);}}},[]);
 useEffect(()=>{const ac=new AbortController();getAnatomy(ac.signal).then(data=>setNeurons(data.neurons)).catch(e=>{if(e.name!=='AbortError')setAnatomyError(e.message);});return()=>ac.abort();},[]);
 useEffect(()=>()=>stopInput(),[stopInput]);
 useEffect(()=>{engine.current.reset();resetTiming.current=true;if(!config.current.playing)publishStill();},[params,publishStill]);
 useEffect(()=>{const ac=new AbortController();const endpoint=import.meta.env.VITE_KICK_STATUS_URL||'';if(!endpoint)return;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const status=await readBroadcastStatus(endpoint,ac.signal);if(!ac.signal.aborted)setBroadcast(status);}catch{if(!ac.signal.aborted)setBroadcast(unknownStatus);}finally{if(!ac.signal.aborted)timer=setTimeout(poll,60000);}};poll();return()=>{ac.abort();clearTimeout(timer);};},[]);
 useEffect(()=>{if(!evidence)return;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';document.getElementById('evidence-choice')?.focus();const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setEvidence(null);return;}if(e.key==='Tab'){const panel=document.querySelector('.evidence-panel');const focusable=Array.from(panel?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],select,input:not(:disabled),[tabindex="0"]')??[]);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&(document.activeElement===first||!panel?.contains(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||!panel?.contains(document.activeElement))){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',close);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',close);previous?.focus();};},[!!evidence]);
 useEffect(()=>{if(mode==='file'||mode==='capture'){if(playing)video.current?.play().catch(()=>{setPlaying(false);setNotice('Video playback needs a click on Play.');});else video.current?.pause();}resetTiming.current=true;},[playing,mode]);
 const switchSource=(target:'sample'|'kick')=>{stopInput();reset();setMode(target);setPlaying(true);setNotice('');if(target==='sample')setDuration(30);};
 const capture=async()=>{
  if(!navigator.mediaDevices?.getDisplayMedia){setNotice('Tab capture is unavailable in this browser. Open this local URL in Chrome or Edge, or choose a local video.');return;}
  setBusy(true);setNotice('Choose the Kick tab in the browser sharing dialog.');
  try{
   const input=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30,max:60}},audio:false});
   stopInput();reset();stream.current=input;video.current!.srcObject=input;await video.current!.play();setMode('capture');setPlaying(true);setNotice('Capturing the source you selected. LIVE CAPTURE describes this connection, not verified Kick broadcast status.');
   input.getVideoTracks()[0].addEventListener('ended',()=>{if(stream.current!==input)return;stream.current=null;setMode('kick');setNotice('Sharing stopped. Share a tab again or use the sample.');reset();},{once:true});
  }catch(e){setNotice(e instanceof Error&&e.name==='NotAllowedError'?'Sharing was cancelled or denied. Your previous source is still available.':`Capture could not start. ${e instanceof Error?e.message:'Try Chrome or Edge.'}`);}finally{setBusy(false);}
 };
 const loadFile=async(file?:File)=>{
  if(!file)return;if(!file.type.startsWith('video/')&&!/\.(mp4|webm|mov|m4v|ogv)$/i.test(file.name)){setNotice('Choose a playable video such as MP4 or WebM.');return;}
  stopInput();reset();objectUrl.current=URL.createObjectURL(file);video.current!.src=objectUrl.current;setFileName(file.name);setMode('file');setNotice('Local video stays on this computer.');setPlaying(true);
  try{await video.current!.play();}catch{setNotice('The browser could not play this file. Try an H.264 MP4 or WebM, or use Sample.');setPlaying(false);}
 };
 useEffect(()=>{
  const small=document.createElement('canvas');small.width=192;small.height=108;const read=small.getContext('2d',{willReadFrequently:true})!;const source=document.createElement('canvas');source.width=768;source.height=432;const sourceCtx=source.getContext('2d')!;
  let raf=0,last=0,lastReport=0,count=0,totalCost=0,videoTime=-1;
  const tick=(now:number)=>{
   raf=requestAnimationFrame(tick);const c=config.current;if(!c.playing||c.mode==='kick'||document.hidden){last=now;lastReport=now;count=0;totalCost=0;return;}if(now-last<1000/30)return;
   if(resetTiming.current){last=now-1000/30;lastReport=now;count=0;totalCost=0;videoTime=-1;resetTiming.current=false;}
   let dt=Math.min(250,now-last);last=now;
   if(c.mode==='sample'){time.current=(time.current+dt/1000)%30;drawSample(sourceCtx,time.current,c.pattern);}
   else {const v=video.current;if(!v||v.readyState<2||v.paused||v.seeking)return;if(v.currentTime===videoTime)return;dt=videoTime<0?1000/30:Math.max(1,(v.currentTime-videoTime)*1000);videoTime=v.currentTime;time.current=v.currentTime;sourceCtx.fillStyle='#090e10';sourceCtx.fillRect(0,0,768,432);const ratio=Math.min(768/v.videoWidth,432/v.videoHeight);sourceCtx.drawImage(v,(768-v.videoWidth*ratio)/2,(432-v.videoHeight*ratio)/2,v.videoWidth*ratio,v.videoHeight*ratio);}
   const start=performance.now();read.drawImage(source,0,0,192,108);engine.current.configure(192,108,c.params);
   try{metrics.current=engine.current.process(read.getImageData(0,0,192,108).data,dt,time.current);}catch{setNotice('Pixel access was blocked. Choose a tab capture or local video.');setPlaying(false);return;}
   original.current?.getContext('2d')?.drawImage(source,0,0);const rc=retina.current?.getContext('2d');if(rc)engine.current.render(rc,c.stage,768,432);
   history.current.push({...metrics.current});if(history.current.length>450)history.current.shift();const chart=trace.current?.getContext('2d');
   if(chart)drawTrace(chart,history.current);
   totalFrames.current++;count++;totalCost+=performance.now()-start;
   if(now-lastReport>350){setStats({metrics:{...metrics.current},fps:count*1000/(now-lastReport),cost:totalCost/count,frames:totalFrames.current});lastReport=now;count=0;totalCost=0;}
  };raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);
 },[]);
 const seek=(value:number)=>{time.current=value;engine.current.reset();resetTiming.current=true;history.current=[];setEnded(false);if(mode==='file'&&video.current)video.current.currentTime=value;if(!playing&&mode==='sample')publishStill(value);else setStats(s=>({...s,metrics:{...s.metrics,time:value}}));};
 const replay=()=>{seek(0);setPlaying(true);};
 const status=mode==='sample'?'SAMPLE':mode==='capture'?'LIVE CAPTURE':mode==='file'?'LOCAL VIDEO':'CAPTURE REQUIRED';
 const response=selectedNeuron?.type.startsWith('T5')?stats.metrics.off:selectedNeuron?.type==='HSE'?stats.metrics.right+stats.metrics.left:stats.metrics.on;
 return <>
 <a className="skip-link" href="#workbench">Skip to workbench</a>
 <header className="app-header" inert={!!evidence}><div className="brand"><Activity size={24}/><h1>FlyStream <span>Lab</span></h1><span className="version">VISUAL SYSTEMS / 0.1</span></div><div className="mode-tabs" aria-label="Experiment mode"><button className={!experiment?'active':''} onClick={()=>setExperiment(false)}>Digital fly</button><button className={experiment?'active':''} onClick={()=>setExperiment(true)}><Camera size={15}/>Real fly experiment</button></div><button className="text-button" onClick={()=>setEvidence(evidence?null:'sampling')}><BookOpen size={16}/>Evidence</button></header>
 <main id="workbench" inert={!!evidence}>
 <div className="source-toolbar"><div className="source-label"><Radio size={16}/><strong>{mode==='sample'?'Test stimulus':mode==='file'?'Local video':mode==='capture'?'Shared tab':'jesusavgn'}</strong><span>{mode==='kick'?'/ Kick':mode==='sample'?'/ synthetic':'/ source'}</span></div><div className="source-actions"><button onClick={()=>switchSource('kick')} className={mode==='kick'?'selected':''}>Kick player <ExternalLink size={14}/></button><button className="primary" disabled={busy} onClick={capture}><Share2 size={15}/>{busy?'Choose a tab…':'Share tab'}</button><button onClick={()=>fileInput.current?.click()}><Upload size={15}/>Local video</button><button className={mode==='sample'?'selected':''} onClick={()=>switchSource('sample')}>Sample</button></div><div className="status" data-status={status}><span className={mode==='capture'?'status-dot':''}/>{status}</div></div>
 <input ref={fileInput} type="file" accept="video/*,.mp4,.webm,.mov" className="hidden" onChange={e=>{loadFile(e.target.files?.[0]);e.target.value='';}}/>
 <video ref={video} muted playsInline className="decoder" onLoadedMetadata={()=>{if(video.current&&Number.isFinite(video.current.duration))setDuration(video.current.duration);}} onEnded={()=>{if(config.current.mode==='file'){setPlaying(false);setEnded(true);}}} onSeeked={()=>{if(config.current.mode==='file'&&!config.current.playing)publishStill(video.current?.currentTime);}} onError={()=>{if(config.current.mode==='file'){setNotice('Video format could not be decoded. Try MP4 / WebM or the sample.');setPlaying(false);}}}/>
 {notice&&<div className="notice" role="status"><span>{notice}</span><button className="icon-button" aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={15}/></button></div>}
 {experiment&&<section className="experiment"><div><h2>Real fly experiment</h2><p>Equipment-dependent mode. Camera tracking can measure body position and orientation relative to a calibrated display. Body direction does not establish attention or conscious watching.</p></div><div><strong>No experimental hardware connected</strong><p>The digital model remains active below. Neural measurement requires calcium imaging, electrophysiology or a published recording dataset. No measured neural activity is generated.</p><span className="classification measured">MEASURED — unavailable</span></div></section>}
 <div className="monitors">
 <section className="monitor source-monitor"><div className="monitor-heading"><h2>Original stream</h2><span className="classification source">SOURCE</span></div><div className="viewport">
 {mode==='kick'?<><iframe key={broadcast.state} title="Official JesusAVGN Kick player" src="https://player.kick.com/jesusavgn?autoplay=false&muted=true" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/><div className="embed-help"><span>{broadcast.state==='UNKNOWN'?'Player reports live / offline':`Kick ${broadcast.state} · verified status service`}</span><a href="https://kick.com/jesusavgn" target="_blank" rel="noreferrer">Open Kick <ExternalLink size={12}/></a></div></>:<><canvas ref={original} width={768} height={432} aria-label="Original processed source frame"/><div className="image-overlay"><span>{mode==='sample'?'SYNTHETIC TEST STIMULUS':mode==='file'?fileName:'USER-SHARED SOURCE'}</span><span>{timecode(stats.metrics.time)}</span></div></>}
 </div><div className="monitor-footer"><span>{mode==='sample'?'Moving contrast · no stream content':mode==='kick'?`Broadcast: ${broadcast.state}${broadcast.checkedAt?' · '+new Date(broadcast.checkedAt).toLocaleTimeString(): ' · check the player'}`:mode==='file'?'Local decoder · no upload':'Browser capture · audio off'}</span><Monitor size={14}/></div></section>
 <section className="monitor"><div className="monitor-heading"><h2>Fly POV</h2><span className="classification modelled">MODELLED</span></div><div className="viewport">{mode==='kick'?<div className="empty-view"><Share2 size={26}/><h3>Frame access required</h3><p>Share the Kick tab to run the visual model on its pixels.</p><button onClick={capture} disabled={busy}>Share tab</button></div>:<><canvas ref={retina} width={768} height={432} aria-label="Modelled retinal stimulus"/><div className="image-overlay"><span>{activeStage.short.toUpperCase()}</span><span>{stats.metrics.samples} samples</span></div></>}</div><div className="monitor-footer"><span>{params.fov}° stimulus patch · UV not recorded</span><button className="icon-button" aria-label="Inspect retinal evidence" onClick={()=>setEvidence(activeStage.evidence)}><BookOpen size={14}/></button></div></section>
 <section className="monitor"><div className="monitor-heading"><h2>Optic lobe</h2><span className={`classification ${overlay&&mode!=='kick'?'inferred':'source'}`}>{overlay&&mode!=='kick'?'SOURCE + INFERRED':'SOURCE'}</span></div><div className="viewport anatomy-viewport">{anatomyError?<div className="empty-view"><h3>Anatomy unavailable</h3><p>{anatomyError}</p><a href="https://v2.virtualflybrain.org/" target="_blank" rel="noreferrer">Open VFB</a></div>:<Anatomy neurons={neurons} selected={selected} onSelect={selectNeuron} metrics={metrics} overlay={overlay&&mode!=='kick'}/>}<div className="selected-anatomy">{selectedNeuron?.type} · {selectedNeuron?.id}</div><div className="activity-label">{overlay&&mode!=='kick'?'SIMULATED ACTIVITY':'STRUCTURAL ANATOMY'}</div></div><div className="monitor-footer"><span>VFB · JRC_Optic-Lobe v1.0.1</span><button className="icon-button" aria-label="Inspect VFB evidence" onClick={()=>setEvidence('workshop')}><BookOpen size={14}/></button></div></section>
 </div>
 <div className="transport"><button className="play-button" aria-label={ended?'Replay source':playing?'Pause processing':'Play processing'} disabled={mode==='kick'} onClick={()=>ended?replay():setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button className="icon-button" aria-label="Restart source" disabled={mode==='capture'||mode==='kick'} onClick={replay}><RotateCcw size={15}/></button><output className="timecode">{timecode(stats.metrics.time)}</output><input aria-label="Source timeline" type="range" min={0} max={mode==='sample'?30:duration} step={.1} value={Math.min(stats.metrics.time,mode==='sample'?30:duration)} disabled={mode==='kick'||mode==='capture'} onChange={e=>seek(+e.target.value)}/><span className="transport-hint">{mode==='capture'?'Live input · no buffer':mode==='kick'?'Waiting for shared frames':playing?'Frames synchronized':'Processing paused'}</span><div className="performance"><span><strong>{playing&&mode!=='kick'?stats.fps.toFixed(0):'—'}</strong> fps</span><span><strong>{stats.cost.toFixed(1)}</strong> ms compute</span></div></div>
 <div className="science-caption"><span>A biologically informed approximation of the visual stimulus available to the fly.</span><button onClick={()=>setEvidence('limits')}>Model limits <ArrowRight size={14}/></button></div>
 <FlyScene source={original} mode={mode} onShare={capture} busy={busy}/>
 <div className="work-area"><section className="processing"><div className="section-title"><h2>Visual processing</h2><button onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><Settings2 size={15}/>Parameters <ChevronDown size={14}/></button></div><div className="stages" aria-label="Visual processing stage">{stages.map((s,i)=><button key={s.id} className={stage===s.id?'active':''} aria-pressed={stage===s.id} onClick={()=>{setStage(s.id);if(evidence)setEvidence(s.evidence);if(retina.current)engine.current.render(retina.current.getContext('2d')!,s.id,768,432);}}><span className="stage-index">{i+1}</span><span>{s.name}</span></button>)}</div><p className="stage-explanation">{activeStage.description}</p>
 {advanced&&<div className="parameters">{([{key:'spacing',label:'Sampling Δφ',min:2,max:8,step:.5,unit:'°'},{key:'acceptance',label:'Acceptance FWHM',min:2,max:10,step:.5,unit:'°'},{key:'fov',label:'Screen angular width',min:40,max:140,step:5,unit:'°'},{key:'delay',label:'Motion delay',min:10,max:100,step:5,unit:'ms'},{key:'adaptation',label:'Adaptation assumption',min:50,max:500,step:25,unit:'ms'},{key:'gain',label:'Display gain',min:1,max:10,step:.5,unit:'×'}] as const).map(p=><label key={p.key}>{p.label}<output>{params[p.key]} {p.unit}</output><input type="range" min={p.min} max={p.max} step={p.step} value={params[p.key]} onChange={e=>{setParams({...params,[p.key]:+e.target.value});engine.current.reset();}}/></label>)}<button onClick={()=>{setParams({...defaults});engine.current.reset();}}>Reset model</button><p>Default optical spacing, acceptance and motion delay follow published models. Screen geometry, adaptation and gain are assumptions. Input frame rate limits temporal information.</p></div>}
 <div className="response-heading"><h3>Stimulus response</h3><span className="legend"><i className="on"/>ON <i className="off"/>OFF <i className="change"/>Frame change</span><span>Shared scale · dimensionless</span></div><div className="trace-wrap"><canvas ref={trace} width={960} height={150} aria-label="Rolling model ON, OFF and frame-change response plot"/><div className="trace-labels"><span>Up to 450 processed frames · temporal history resets on seek</span><span>Now</span></div></div>
 <div className="readouts"><div><span>Mean luminance</span><strong>{stats.metrics.luminance.toFixed(3)}</strong></div><div><span>Spatial RMS</span><strong>{stats.metrics.contrast.toFixed(3)}</strong></div><div className="motion-readout"><span>Motion energy</span><div>{[[ArrowRight,'right'],[ArrowLeft,'left'],[ArrowUp,'up'],[ArrowDown,'down']].map(([Icon,key])=>{const I=Icon as typeof ArrowRight;return <span key={key as string} ><span className="sr-only">{`${key} motion energy `}</span><I size={13} aria-hidden="true"/>{(stats.metrics[key as keyof Metrics]).toFixed(3)}</span>;})}</div></div></div>
 {mode==='sample'&&<div className="sample-controls"><label htmlFor="sample-pattern">Test stimulus</label><select id="sample-pattern" value={pattern} onChange={e=>{setPattern(e.target.value);reset();}}><option value="grating">Drifting grating / reverses every 10 s</option><option value="edge">Moving bright bar</option><option value="loom">Expanding dark disc</option><option value="static">Stationary checkerboard</option></select><button onClick={async()=>{try{const r=await fetch('/sample.webm');if(!r.ok)throw new Error();await loadFile(new File([await r.blob()],'Synthetic sample clip.webm',{type:'video/webm'}));}catch{setNotice('Sample clip unavailable. The generated test stimulus still works.');}}}>Sample clip</button></div>}
 </section>
 <aside className="neuron-inspector"><div className="section-title"><h2>Neuron inspector</h2><span className="classification source">SOURCE ANATOMY</span></div><div className="neuron-tabs" aria-label="Select neuron">{neurons.map(n=><button key={n.id} className={selected===n.id?'active':''} aria-pressed={selected===n.id} onClick={()=>setSelected(n.id)}>{n.type}</button>)}</div>{selectedNeuron?<><div className="neuron-identity"><h3>{selectedNeuron.type}<span>{selectedNeuron.type.startsWith('T4')?'ON pathway':selectedNeuron.type.startsWith('T5')?'OFF pathway':selectedNeuron.type==='HSE'?'Horizontal system':'Upstream pathway'}</span></h3><a href={selectedNeuron.vfbUrl} target="_blank" rel="noreferrer">{selectedNeuron.id}<ExternalLink size={12}/></a></div><p className="canonical">{selectedNeuron.name}</p><div className="neuron-properties"><span>Dataset</span><strong>JRC_Optic-Lobe v1.0.1</strong><span>Transmitter</span><strong>{selectedNeuron.neurotransmitter?`${selectedNeuron.neurotransmitter.name} (predicted)`:'Not annotated in this record'}</strong><span>Reconstruction</span><strong>Roughly traced · CC-BY 4.0</strong></div><div className="connections"><h4>Verified structural connections</h4>{[...(selectedNeuron.upstream||[]).map(c=>({...c,direction:'input'})),...(selectedNeuron.downstream||[]).map(c=>({...c,direction:'output'}))].map(c=><button key={c.id+c.direction} onClick={()=>setSelected(c.id)}><span>{c.direction==='input'?<ArrowRight size={13}/>:<ArrowLeft size={13}/>} {c.name.split('_R')[0]} <small>{c.direction}</small></span><span>{c.synapses} synapses</span></button>)}<p>Selected partners only. Counts are anatomical; not physiological weights.</p></div><div className="activity-inspector"><label><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/>Show simulated activity</label><div><strong>{mode==='kick'?'—':response.toFixed(3)}</strong><span>{selectedNeuron.type==='HSE'?'pooled horizontal motion':selectedNeuron.type.startsWith('T5')?'OFF contrast drive':'ON contrast drive'}</span></div><p>Why it changes: {selectedNeuron.type==='HSE'?'the sum of left and right motion features changes.':selectedNeuron.type.startsWith('T5')?'samples become darker than their adapting baseline.':'samples become brighter than their adapting baseline.'} This is a feature overlay on an example cell, not its predicted firing rate or a fitted circuit.</p></div></>:<p>{anatomyError||'Reading VFB catalogue…'}</p>}</aside></div>
 <footer className="app-footer"><span><span className="classification source">SOURCE</span>input / anatomy</span><span><span className="classification modelled">MODELLED</span>visual transform</span><span><span className="classification inferred">INFERRED</span>feature response</span><span><span className="classification measured">MEASURED</span>no neural recording</span><a href="https://workshop.virtualflybrain.org/" target="_blank" rel="noreferrer">NeuroFly 2026 <ExternalLink size={12}/></a></footer>
 </main>
 {evidence&&<aside className="evidence-panel" role="dialog" aria-modal="true" aria-labelledby="evidence-title"><div className="evidence-heading"><BookOpen size={20}/><h2 id="evidence-title">Evidence inspector</h2><button className="icon-button" aria-label="Close evidence inspector" onClick={()=>setEvidence(null)}><X size={19}/></button></div><label htmlFor="evidence-choice">Inspect a model or source</label><select id="evidence-choice" value={evidence} onChange={e=>setEvidence(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>{currentEvidence&&<><span className="evidence-kind">{currentEvidence.category}</span><h3>{currentEvidence.title}</h3><p>{currentEvidence.detail}</p><a href={currentEvidence.url} target="_blank" rel="noreferrer">{currentEvidence.citation}<ExternalLink size={14}/></a></>}<hr/><h3>Structural data</h3><p>Six reconstructed neurons from JRC_Optic-Lobe v1.0.1, registered to JRC2018Unisex. Queried through VFB MCP on 16 September 2026.</p><a href="https://doi.org/10.1038/s41586-025-08746-0" target="_blank" rel="noreferrer">Nern et al. · Nature · 2025 <ExternalLink size={14}/></a><p className="evidence-warning">No experimental neuronal time series is connected. Anatomical edges and synapse counts cannot turn this model into a measurement.</p><a href="/data/neurons.json" download>Download provenance / VFB records</a></aside>}
 </>;
}


